name: Terraform CI

on:
  push:
    paths:
      - '*.tf'
      - '**/*.tf'
      - '.github/workflows/terraform.yml'

  pull_request:
    paths:
      - '**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Lambda ZIPs
        run: |
          echo "Zipping Lambda functions..."

          mkdir -p build

          # Create Order Lambda
          cd lambdas/create_order
          npm install
          zip -r ../../build/lambda_create_order.zip .
          cd ../..

          # OrderCreated Handler Lambda
          cd lambdas/order_created_handler
          npm install
          zip -r ../../build/lambda_order_created_handler.zip .
          cd ../..

          # Payment Processor Lambda
          cd lambdas/payment_processor
          npm install
          zip -r ../../build/lambda_payment_processor.zip .
          cd ../..

          echo "Lambda ZIPs created in ./build"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init (Lab 1)
        run: terraform init -input=false

      - name: Terraform Validate (Lab 1)
        run: terraform validate

      - name: Terraform Plan (Lab 1)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: |
          terraform plan -input=false \
            -var "db_username=${DB_USERNAME}" \
            -var "db_password=${DB_PASSWORD}" \
            -var "notification_email=${NOTIFICATION_EMAIL}"

      - name: Terraform Apply (Lab 1)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: |
          terraform apply -auto-approve \
            -var "db_username=${DB_USERNAME}" \
            -var "db_password=${DB_PASSWORD}" \
            -var "notification_email=${NOTIFICATION_EMAIL}"

            



  # - name: Terraform Init (Lab 2)
     #   working-directory: ./lab2_order_system
     #   run: terraform init -input=false

     # - name: Terraform Validate (Lab 2)
      #  working-directory: ./lab2_order_system
     #   run: terraform validate

    #  - name: Terraform Plan (Lab 2)
      #  working-directory: ./lab2_order_system
     #   env:
   #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
 #       run: terraform plan -input=false
